# @package _global_
env:
  name: "MiniGrid-DoorKey-6x6-v0" # Environment name
  wrapper: "FlatObsWrapper" # FlatObsWrapper or RGBImgObsWrapper

seed: 1   # Random seed for reproducibility

agent:
  type:                   "dqn"   # Possebile values: "dqn", "rnd"
  buffer_capacity:        76350   # Max replay buffer size
  batch_size:             128      # Minibatch size
  gamma:                  0.95    # Discount factor
  epsilon_start:          1.0     # Initial value of epsilon
  epsilon_final:          0.04    # Final value of epsilon
  epsilon_decay:          28006    # Decay steps for epsilon
  dqn_hidden_size:        64      # Hidden size for DQN networks
  dqn_lr:                 0.0004   # Maps to DQNAgentâ€™s lr
  dqn_target_update_freq: 101    # Update target network every this many steps
  
train:
  num_frames:             10000  # Total env steps
  vmap_save_every_n:      50000   # Save visitation map every nth step to reduce file size.
  minibatch_window:       250     # Rolling window size for averaging minibatch values.
  minibatch_save_every_n: 50      # Save minibatch values every nth step to reduce file size.
  eval_interval:          10      # Print average episode reward every eval_interval steps in terminal.
  saved_decimals:         5       # number of decimals saved in the csv